### ISSUE TITLE
Double click on hierarchy class should expand list

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#156]
When you have a hierarchy view open on a class, it would be handy to be able to double click on any class in the hierarchy and the view should expand the hierarchy for that class.

**Comment by ericwinger** [comment]
Fixed in 3.0.32. 

@LisaAlmarode  fyi - I'm aware that double clicking Object seems to take two tries. Somehow the double click is getting lost or interrupted on the first attempt. We can make a new issue for that if the double-click expand looks otherwise ok.

**Comment by LisaAlmarode** [comment]
It expands the hierarchy, but by one level.  Which is okay.  However, it does not display the little + indicating further expansion.

Specifically, I'm looking at Collection classes that have extension methods in collection classes, STON | STON-GemStoneCommon.  The hierarchy view doesn't have + by CharacterCollection since that's a terminal class within the package (OK) 

When you double click on it, it shows CharacterCollection subclasses but there is no + next to Multi ByteString, which hides the existence of DoubleByteString.

Either full expansion or one level with + would be okay, but it's awkward as is,  This is pretty minor.

**Comment by ericwinger** [comment]
Believe I have a fix for the > display when no classes are selected and the hierarchy tab is chosen. 
3.0.44

**Comment by LisaAlmarode** [comment]
I complained about the lack of the little plus next to a class to indicate an unexpanded sub-hierarchy.  this is still present in 3.0.45.  It's definitely not something worth holding up release for.

In the following example, CharacterCollection was not expanded when I went to the heirarchy view.  I double-clicked on CharacterCollection.  You can't tell that MultiByteString has subclasses - there's no little plus.  

![image](https://user-images.githubusercontent.com/13142166/47889144-a6d54e80-de05-11e8-919a-87f529b77667.png)

**Comment by LisaAlmarode** [comment]
Closing this.  The but itself is fixed; the ability to see the existence of siblings is still a problem in 3.0.74, but is probably quite effortful to deal with.  Will file a new, separate issue after discussion with Eric, next time I'm very annoyed.
